num1=int(input('me fale um numero '))
num2=int(input('me outro numero '))
result=(num1 + num2)
print(type(result))
#print('a soma entre o', num1,'e o',num2, 'é',result, ', correto?')
#print('o resultado da soma é {} certo?'.format(result))
print('então a soma entre {} e {} é igual a {}, correto?'.format(num1, num2, result))
